# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../flutter_offerwall_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'IOSExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOSExample
  install_all_flutter_pods(flutter_application_path)
  

end
post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386, arm64"
  end
end
